language: python

branches:
    only:
        - source

install:
    - pip install Sphinx travis-sphinx recommonmark

script:
    - .ci/retrieve_readme.sh
    - .ci/retrieve_wiki.sh
    - travis-sphinx build

after_success:
    - travis-sphinx deploy
